// AUTO-GENERATED — do not edit manually.
// Generated by scripts/generate-version.mjs from package.json version "3.0.0-dev.0".
// Re-run `npm run gen:version` after bumping package.json.
export const VERSION = "3.0.0-dev.0";
