// AUTO-GENERATED — do not edit manually.
// Generated by scripts/generate-version.mjs from package.json version "2.1.0".
// Re-run `npm run gen:version` after bumping package.json.
export const VERSION = "2.1.0";
