// version.ts - Shared runtime version injected from package.json at build time.
// The version is generated by scripts/generate-version.mjs into version.generated.ts
// (VERSION is a static string literal, not a runtime fs read). This keeps the
// source free of hardcoded version strings while avoiding the fragile
// `readFileSync(new URL('../../package.json', import.meta.url))` pattern that
// broke when `dist/` was executed from different working directories or bundled.
// Run `npm run gen:version` after bumping package.json.

import { VERSION } from './version.generated.js';

export { VERSION };

export function getVersion(): string {
  return VERSION;
}

// test seam: kept for backward compat; previously reset the fs-read cache.
// Now a no-op because VERSION is a build-time constant.
export function __resetVersionCache(): void {}
