#!/usr/bin/env node
// generate-version.mjs - Inject package.json version into src/protocol/version.generated.ts
// This avoids hardcoding the version and avoids runtime fs reads.
// Run via `npm run gen:version` or automatically via `prebuild`.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const pkgPath = resolve(root, 'package.json');
const outPath = resolve(root, 'src/protocol/version.generated.ts');

let version = '?';
try {
  const raw = readFileSync(pkgPath, 'utf8');
  const pkg = JSON.parse(raw);
  version = typeof pkg.version === 'string' && pkg.version !== '' ? pkg.version : '?';
} catch (err) {
  console.error(`[gen:version] failed to read ${pkgPath}: ${err instanceof Error ? err.message : String(err)}`);
  process.exit(1);
}

const content = `// AUTO-GENERATED — do not edit manually.
// Generated by scripts/generate-version.mjs from package.json version "${version}".
// Re-run \`npm run gen:version\` after bumping package.json.
export const VERSION = ${JSON.stringify(version)};\n`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, content, 'utf8');
console.log(`[gen:version] ${version} -> src/protocol/version.generated.ts`);
